### ISSUE TITLE
[Fix] 내 계좌로 돈이 동시 송금될 경우 동시성 제어 버그

### ISSUE THREAD

**Issue by chaeyeon-yang** [BangCrush/BankAI-Backend#66]
## 📌 Issue

<img width="776" alt="스크린샷 2024-06-07 오전 11 31 51" src="https://github.com/BangCrush/BankAI-Backend/assets/69382168/80fbb727-de93-46e8-ae18-3f987e2dc24a">

## 📜 To-do

- [x] 동시에 두 개 이상의 다른 계좌에서 돈이 들어올 경우 동시성 제어 필요합니다!

**Comment by soyeonvv** [comment]
해결 - 분산락 적용시 분산락 키를 출금 계좌에서 출금 + 입금 계좌로 변경
